import { datePickerAnatomy } from "@ark-ui/react/date-picker";
import { defineSlotRecipe } from "@pandacss/dev";

export const datePicker = defineSlotRecipe({
  className: "date-picker",
  slots: datePickerAnatomy.keys(),
  base: {
    root: {
      display: "flex",
      flexDirection: "column",
      gap: "1.5",
      w: "full",
    },
    label: {
      color: "fg.default",
      fontWeight: "medium",
      textStyle: "sm",
    },
    control: {
      display: "flex",
      gap: "2",
    },
    input: {
      appearance: "none",
      bg: "bg.default",
      borderColor: "border.default",
      borderRadius: "lg",
      borderWidth: "1px",
      color: "fg.default",
      flex: "1",
      minW: "0",
      outline: "0",
      transitionDuration: "normal",
      transitionProperty: "background-color, border-color, color, box-shadow",
      w: "full",
      _placeholder: { color: "fg.subtle" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "colorPalette.solid.bg",
        outlineOffset: "1px",
      },
    },
    trigger: {
      alignItems: "center",
      appearance: "none",
      bg: "bg.default",
      borderColor: "border.default",
      borderRadius: "lg",
      borderWidth: "1px",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      flexShrink: "0",
      justifyContent: "center",
      outline: "0",
      transitionDuration: "normal",
      transitionProperty: "background-color, border-color, color, box-shadow",
      _hover: { bg: "bg.subtle" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "colorPalette.solid.bg",
        outlineOffset: "1px",
      },
    },
    positioner: {
      zIndex: "50",
    },
    content: {
      bg: "bg.default",
      borderColor: "border.subtle",
      borderRadius: "lg",
      borderWidth: "1px",
      boxShadow: "lg",
      display: "flex",
      flexDirection: "column",
      gap: "3",
      outline: "0",
      p: "3",
      _hidden: { display: "none" },
    },
    view: {
      display: "flex",
      flexDirection: "column",
      gap: "3",
    },
    viewControl: {
      alignItems: "center",
      display: "flex",
      gap: "2",
      justifyContent: "space-between",
    },
    viewTrigger: {
      alignItems: "center",
      borderRadius: "md",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      fontWeight: "medium",
      gap: "1",
      h: "8",
      px: "2",
      textStyle: "sm",
      _hover: { bg: "bg.subtle" },
    },
    rangeText: {
      whiteSpace: "nowrap",
    },
    prevTrigger: {
      alignItems: "center",
      borderRadius: "md",
      boxSize: "8",
      color: "fg.muted",
      cursor: "pointer",
      display: "inline-flex",
      justifyContent: "center",
      _hover: { bg: "bg.subtle", color: "fg.default" },
      _disabled: { color: "fg.disabled", cursor: "not-allowed" },
    },
    nextTrigger: {
      alignItems: "center",
      borderRadius: "md",
      boxSize: "8",
      color: "fg.muted",
      cursor: "pointer",
      display: "inline-flex",
      justifyContent: "center",
      _hover: { bg: "bg.subtle", color: "fg.default" },
      _disabled: { color: "fg.disabled", cursor: "not-allowed" },
    },
    table: {
      borderCollapse: "separate",
      borderSpacing: "1",
      m: "-1",
      w: "full",
    },
    tableHeader: {
      color: "fg.muted",
      fontWeight: "medium",
      h: "8",
      textStyle: "xs",
    },
    tableCell: {
      textAlign: "center",
    },
    tableCellTrigger: {
      alignItems: "center",
      borderRadius: "md",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      h: "9",
      justifyContent: "center",
      minW: "9",
      textStyle: "sm",
      transitionDuration: "fast",
      transitionProperty: "background-color, color",
      w: "full",
      _hover: { bg: "bg.subtle" },
      _selected: {
        bg: "colorPalette.solid.bg",
        color: "colorPalette.solid.fg",
        _hover: { bg: "colorPalette.solid.bg.hover" },
      },
      _disabled: {
        color: "fg.disabled",
        cursor: "not-allowed",
        _hover: { bg: "transparent" },
      },
      "&[data-today]:not([data-selected])": {
        color: "colorPalette.solid.bg",
        fontWeight: "semibold",
      },
      "&[data-outside-range]": {
        color: "fg.subtle",
      },
    },
  },
  variants: {
    size: {
      sm: {
        input: { h: "9", px: "3", textStyle: "sm" },
        trigger: { boxSize: "9" },
      },
      md: {
        input: { h: "10", px: "3", textStyle: "sm" },
        trigger: { boxSize: "10" },
      },
      lg: {
        input: { h: "11", px: "3.5", textStyle: "md" },
        trigger: { boxSize: "11" },
      },
    },
  },
  defaultVariants: { size: "md" },
});
