import { numberInputAnatomy } from "@ark-ui/react/number-input";
import { defineSlotRecipe } from "@pandacss/dev";

export const numberInput = defineSlotRecipe({
  className: "number-input",
  slots: numberInputAnatomy.keys(),
  base: {
    root: {
      display: "flex",
      flexDirection: "column",
      gap: "1.5",
      w: "full",
    },
    label: {
      color: "fg.default",
      fontWeight: "medium",
      textStyle: "sm",
    },
    control: {
      bg: "bg.default",
      borderColor: "border.default",
      borderRadius: "lg",
      borderWidth: "1px",
      display: "grid",
      gridTemplateColumns: "1fr token(sizes.8)",
      gridTemplateRows: "1fr 1fr",
      overflow: "hidden",
      transitionDuration: "normal",
      transitionProperty: "background-color, border-color, color, box-shadow",
      _focusWithin: {
        outline: "2px solid",
        outlineColor: "colorPalette.solid.bg",
        outlineOffset: "1px",
      },
    },
    input: {
      appearance: "none",
      bg: "transparent",
      border: "none",
      color: "fg.default",
      gridRow: "span 2",
      minW: "0",
      outline: "0",
      w: "full",
      _placeholder: { color: "fg.subtle" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
    },
    incrementTrigger: {
      alignItems: "center",
      borderColor: "border.default",
      borderStartWidth: "1px",
      color: "fg.muted",
      cursor: "pointer",
      display: "inline-flex",
      justifyContent: "center",
      transitionDuration: "fast",
      transitionProperty: "background-color, color",
      _hover: { bg: "bg.subtle", color: "fg.default" },
      _disabled: { color: "fg.disabled", cursor: "not-allowed" },
    },
    decrementTrigger: {
      alignItems: "center",
      borderColor: "border.default",
      borderStartWidth: "1px",
      borderTopWidth: "1px",
      color: "fg.muted",
      cursor: "pointer",
      display: "inline-flex",
      justifyContent: "center",
      transitionDuration: "fast",
      transitionProperty: "background-color, color",
      _hover: { bg: "bg.subtle", color: "fg.default" },
      _disabled: { color: "fg.disabled", cursor: "not-allowed" },
    },
  },
  variants: {
    size: {
      sm: { control: { h: "9" }, input: { px: "3", textStyle: "sm" } },
      md: { control: { h: "10" }, input: { px: "3", textStyle: "sm" } },
      lg: { control: { h: "11" }, input: { px: "3.5", textStyle: "md" } },
    },
  },
  defaultVariants: { size: "md" },
});
